### ISSUE TITLE
Create packages so don't have to compile from source

### ISSUE THREAD

**Issue by spuder** [deep011/redis-cluster-tool#2]
Any plans to release this in a package so that you don't have to compile from source? 

This would allow for easy deployments using configuration management tools ([Ansible](http://www.ansible.com/), [CHEF](https://www.chef.io/), [Puppet](https://puppetlabs.com/), [Salt](http://saltstack.com/)). Especially useful if you want to deploy the tool to multiple datacenters without having to ssh into each node. 

The package could easily be created using [fpm](https://github.com/jordansissel/fpm) and then uploaded to [packagecloud](https://packagecloud.io/)

**Comment by deep011** [comment]
This is a good idea!
I have add "redis-cluster-tool-0.1.0-1.el6.x86_64.rpm" to packagecloud.
You can try it first!

Before yum install redis-cluster-tool, please execute the follow command:
"curl -s https://packagecloud.io/install/repositories/deep/packages/script.rpm.sh | sudo bash"

**Comment by spuder** [comment]
This is great. Any plans for an Ubuntu package? I don't have any centos machines.

**Comment by deep011** [comment]
Yes, other os packages will be upload later.

**Comment by deep011** [comment]
ubuntu 14.04 is supported.

Before apt-get install redis-cluster-tool, execute "curl -s https://packagecloud.io/install/repositories/deep/packages/script.deb.sh | sudo bash".

**Comment by spuder** [comment]
The ubuntu one works perfectly, handles the dependency and everything. 

The following chef recipe works

``` ruby
packagecloud_repo "deep/packages" do
  type "deb"
end

package 'redis-cluster-tool' do
  action :install
end
```
