### ISSUE TITLE
rct_core.c:5384: error: too many arguments to function ‘ctx_get_by_node’

### ISSUE THREAD

**Issue by Layamon** [deep011/redis-cluster-tool#9]

**Comment by Layamon** [comment]
[lym@localhost src]$ cd redis-cluster-tool/
[lym@localhost redis-cluster-tool]$ ls
ae  config.h  Makefile  rct.c  rct_command.c  rct_command.h  rct_core.c  rct_core.h  rct_locklist.c  rct_locklist.h  rct_log.c  rct_log.h  rct_mttlist.c  rct_mttlist.h  rct_option.c  rct_option.h  rct_util.c  rct_util.h  README.md
[lym@localhost redis-cluster-tool]$ make
cc -I/usr/local/include/hiredis-vip -I./ae   -c -o rct.o rct.c
cc -I/usr/local/include/hiredis-vip -I./ae   -c -o rct_command.o rct_command.c
cc -I/usr/local/include/hiredis-vip -I./ae   -c -o rct_core.o rct_core.c
rct_core.c: In function ‘nodes_keys_num’:
rct_core.c:651: warning: passing argument 1 of ‘ctx_get_by_node’ from incompatible pointer type
/usr/local/include/hiredis-vip/hircluster.h:131: note: expected ‘struct redisClusterContext *’ but argument is of type ‘struct cluster_node *’
rct_core.c:651: error: too many arguments to function ‘ctx_get_by_node’
rct_core.c: In function ‘node_key_num’:
rct_core.c:769: warning: passing argument 1 of ‘ctx_get_by_node’ from incompatible pointer type
/usr/local/include/hiredis-vip/hircluster.h:131: note: expected ‘struct redisClusterContext *’ but argument is of type ‘struct cluster_node *’
rct_core.c:769: error: too many arguments to function ‘ctx_get_by_node’
rct_core.c: In function ‘node_memory_size’:
rct_core.c:900: warning: passing argument 1 of ‘ctx_get_by_node’ from incompatible pointer type
/usr/local/include/hiredis-vip/hircluster.h:131: note: expected ‘struct redisClusterContext *’ but argument is of type ‘struct cluster_node *’
rct_core.c:900: error: too many arguments to function ‘ctx_get_by_node’
rct_core.c: In function ‘node_cluster_state’:
rct_core.c:1031: warning: passing argument 1 of ‘ctx_get_by_node’ from incompatible pointer type
/usr/local/include/hiredis-vip/hircluster.h:131: note: expected ‘struct redisClusterContext *’ but argument is of type ‘struct cluster_node *’
rct_core.c:1031: error: too many arguments to function ‘ctx_get_by_node’
rct_core.c: In function ‘do_command_with_node’:
rct_core.c:1437: warning: passing argument 1 of ‘ctx_get_by_node’ from incompatible pointer type
/usr/local/include/hiredis-vip/hircluster.h:131: note: expected ‘struct redisClusterContext *’ but argument is of type ‘struct cluster_node *’
rct_core.c:1437: error: too many arguments to function ‘ctx_get_by_node’
rct_core.c: In function ‘redis_cluster_addr_cmp’:
rct_core.c:2377: warning: initialization discards qualifiers from pointer target type
rct_core.c:2377: warning: initialization discards qualifiers from pointer target type
rct_core.c: In function ‘scan_keys_job_one_node’:
rct_core.c:5384: warning: passing argument 1 of ‘ctx_get_by_node’ from incompatible pointer type
/usr/local/include/hiredis-vip/hircluster.h:131: note: expected ‘struct redisClusterContext *’ but argument is of type ‘struct cluster_node *’
rct_core.c:5384: error: too many arguments to function ‘ctx_get_by_node’
make: *** [rct_core.o] Error 1

**Comment by Layamon** [comment]
编译有问题呢

**Comment by deep011** [comment]
代码更新了下，原因是其依赖的hiredis-vip库有变动。

**Comment by Layamon** [comment]
@deep011 多谢
